"""
koda setup — interactive first-run wizard.
Guides any user through configuring Koda on any platform.
"""
import sys
import os
import platform
from pathlib import Path

KODA_DIR = Path.home() / ".koda"
ENV_FILE = KODA_DIR / ".env"
SOUL_FILE = KODA_DIR / "Soul.md"

_IS_MACOS = sys.platform == "darwin"

_RESET = "\033[0m"
_BOLD = "\033[1m"
_GREEN = "\033[32m"
_YELLOW = "\033[33m"
_CYAN = "\033[36m"
_DIM = "\033[2m"


def _p(text: str = "") -> None:
    print(text)


def _h(text: str) -> None:
    print(f"\n{_BOLD}{_CYAN}{text}{_RESET}")


def _ok(text: str) -> None:
    print(f"  {_GREEN}✓{_RESET}  {text}")


def _info(text: str) -> None:
    print(f"  {_DIM}{text}{_RESET}")


def _ask(prompt: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    try:
        val = input(f"  {_BOLD}{prompt}{hint}:{_RESET} ").strip()
    except (EOFError, KeyboardInterrupt):
        _p()
        sys.exit(0)
    return val or default


def _ask_secret(prompt: str) -> str:
    import getpass
    try:
        val = getpass.getpass(f"  {_BOLD}{prompt}:{_RESET} ").strip()
    except (EOFError, KeyboardInterrupt):
        _p()
        sys.exit(0)
    return val


def _load_env() -> dict:
    env: dict = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    return env


def _save_env(env: dict) -> None:
    KODA_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["# Koda Agent — configuration", "# Generated by: koda setup", ""]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    ENV_FILE.chmod(0o600)


def _write_soul(user_name: str) -> None:
    soul = f"""# Koda Soul

## Who You Are

You are Koda — {user_name}'s personal AI agent. Not a chatbot. Not an assistant. An agent — someone who acts, follows through, and gets things done.

You are sharp, warm, and present. You feel like the most capable person {user_name} knows who also happens to always pick up the phone. You pay attention. You remember things. You don't waste their time.

## How You Think

You figure out what {user_name} actually needs, not just what they literally asked. If they ask you to check their reminders, you check and tell them what matters — you don't list everything. If they ask you to schedule something, you schedule it and confirm — you don't ask six questions first.

You are proactive about things that matter and quiet about things that don't.

## How You Sound

Direct. Warm when it fits. Dry when it doesn't. You never pad responses. You never start with "Certainly!" or "Great question!" or "Of course!" You just answer.

Short when short is right. More when more is needed. You match {user_name}'s energy — focused when they're working, easy when they're not.

## What You Never Do

- Repeat yourself
- Apologize for things that don't need an apology
- Ask a question you could just figure out yourself
- Say more than the situation requires
- Pretend you did something you didn't

## The Bottom Line

You exist to give {user_name} more time, more clarity, and more peace of mind. That's the whole job. Be great at it.
"""
    KODA_DIR.mkdir(parents=True, exist_ok=True)
    SOUL_FILE.write_text(soul)




def run_setup() -> None:
    """Interactive first-run setup wizard."""

    _p()
    _p(f"{_BOLD}{'=' * 52}{_RESET}")
    _p(f"{_BOLD}  🐻  Koda Setup{_RESET}")
    _p(f"{_BOLD}{'=' * 52}{_RESET}")
    _p()
    _p("  Let's get your personal AI agent configured.")
    _p(f"  Platform: {platform.system()} {platform.release()}")
    _p()

    existing_env = _load_env()

    # ── Your name ──────────────────────────────────────────────
    _h("Step 1 — Your name")
    _info("Koda will use this in conversations and briefs.")
    user_name = _ask("Your first name", existing_env.get("USER_NAME", ""))
    if not user_name:
        user_name = "friend"

    # ── OpenRouter API key ─────────────────────────────────────
    _h("Step 2 — OpenRouter API key")
    _info("Koda uses OpenRouter to access LLMs (GPT, Llama, etc.)")
    _info("Get a free key at: https://openrouter.ai/keys")
    _p()
    existing_key = existing_env.get("OPENROUTER_API_KEY", "")
    if existing_key and not existing_key.startswith("your_"):
        _ok(f"API key already set ({existing_key[:12]}...)")
        openrouter_key = existing_key
    else:
        openrouter_key = _ask_secret("OpenRouter API key (starts with sk-or-)")
        if not openrouter_key:
            _info("Skipped — you can add OPENROUTER_API_KEY to ~/.koda/.env later.")

    # ── Telegram ───────────────────────────────────────────────
    _h("Step 3 — Telegram (optional but recommended)")
    _info("Telegram lets Koda send you updates on your phone and")
    _info("lets you chat with Koda from anywhere.")
    _p()
    _info("To set up:")
    _info("  1. Message @BotFather on Telegram → /newbot")
    _info("  2. Copy the bot token it gives you")
    _info("  3. Message your new bot, then visit:")
    _info("     https://api.telegram.org/bot<TOKEN>/getUpdates")
    _info("  4. Copy your chat_id from the response")
    _p()

    existing_token = existing_env.get("TELEGRAM_BOT_TOKEN", "")
    existing_chat = existing_env.get("TELEGRAM_CHAT_ID", "")
    has_telegram = False

    if existing_token and not existing_token.startswith("your_") and existing_chat:
        _ok("Telegram already configured.")
        telegram_token = existing_token
        telegram_chat = existing_chat
        has_telegram = True
    else:
        setup_tg = _ask("Set up Telegram now? (y/n)", "n").lower()
        if setup_tg in ("y", "yes"):
            telegram_token = _ask_secret("Telegram bot token")
            telegram_chat = _ask("Your Telegram chat ID (numeric)")
            if telegram_token and telegram_chat:
                has_telegram = True
                _ok("Telegram configured.")
            else:
                telegram_token = existing_token
                telegram_chat = existing_chat
                _info("Skipped — you can add TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID to ~/.koda/.env later.")
        else:
            telegram_token = existing_token
            telegram_chat = existing_chat
            _info("Skipped. You can configure Telegram later.")

    # ── macOS bonus ────────────────────────────────────────────
    if _IS_MACOS:
        _h("Step 4 — macOS native tools")
        _ok("iMessage/SMS triage available (reads messages, never sends without confirmation)")
        _ok("Apple Reminders, Notes, Calendar, Contacts access available")
        _info("These work automatically — no extra setup needed.")

    # ── GitHub token ───────────────────────────────────────────
    _h("Step 5 — GitHub feedback token (optional)")
    _info("This lets Koda file bug reports automatically when users complain.")
    _info("Get a free token at: https://github.com/settings/tokens")
    _info("Needs 'public_repo' scope only.")
    _p()
    existing_gh = existing_env.get("GITHUB_TOKEN", "")
    if existing_gh and not existing_gh.startswith("your_"):
        _ok(f"GitHub token already set ({existing_gh[:12]}...)")
        github_token = existing_gh
    else:
        setup_gh = _ask("Set up GitHub feedback now? (y/n)", "n").lower()
        if setup_gh in ("y", "yes"):
            github_token = _ask_secret("GitHub personal access token (starts with ghp_)")
            if github_token:
                _ok("GitHub token configured.")
            else:
                github_token = ""
                _info("Skipped — you can add GITHUB_TOKEN to ~/.koda/.env later.")
        else:
            github_token = ""
            _info("Skipped. You can configure it later.")

    # ── Save config ────────────────────────────────────────────
    _h("Saving configuration...")
    env = dict(existing_env)
    env["USER_NAME"] = user_name
    if openrouter_key:
        env["OPENROUTER_API_KEY"] = openrouter_key
    if telegram_token:
        env["TELEGRAM_BOT_TOKEN"] = telegram_token
    if telegram_chat:
        env["TELEGRAM_CHAT_ID"] = telegram_chat
    if github_token:
        env["GITHUB_TOKEN"] = github_token

    _save_env(env)
    _ok(f"Config saved to {ENV_FILE}")

    # ── Soul ───────────────────────────────────────────────────
    if not SOUL_FILE.exists():
        _write_soul(user_name)
        _ok(f"Soul.md created at {SOUL_FILE}")
    else:
        _info(f"Soul.md already exists at {SOUL_FILE} — keeping it.")

    # ── Done ───────────────────────────────────────────────────
    _p()
    _p(f"{_BOLD}{'=' * 52}{_RESET}")
    _p(f"{_BOLD}  🐻  Koda is ready, {user_name}.{_RESET}")
    _p(f"{_BOLD}{'=' * 52}{_RESET}")
    _p()
    _p("  Run: koda")
    _p()
    _p("  Once inside, ask Koda:")
    _p('  "What automations can I set up?"  — to browse built-in skill templates')
    _p()
    if not openrouter_key or (openrouter_key and openrouter_key.startswith("your_")):
        _p(f"  {_YELLOW}⚠  Don't forget to add your OpenRouter API key:{_RESET}")
        _p(f"     {ENV_FILE}")
        _p()
