"""
koda setup — interactive first-run wizard.
Guides any user through configuring Koda on any platform.
"""
import sys
import os
import platform
from pathlib import Path

KODA_DIR = Path.home() / ".koda"
ENV_FILE = KODA_DIR / ".env"
SOUL_FILE = KODA_DIR / "Soul.md"

_IS_MACOS = sys.platform == "darwin"

_RESET = "\033[0m"
_BOLD = "\033[1m"
_GREEN = "\033[32m"
_YELLOW = "\033[33m"
_CYAN = "\033[36m"
_DIM = "\033[2m"


def _p(text: str = "") -> None:
    print(text)


def _h(text: str) -> None:
    print(f"\n{_BOLD}{_CYAN}{text}{_RESET}")


def _ok(text: str) -> None:
    print(f"  {_GREEN}✓{_RESET}  {text}")


def _info(text: str) -> None:
    print(f"  {_DIM}{text}{_RESET}")


def _ask(prompt: str, default: str = "") -> str:
    hint = f" [{default}]" if default else ""
    try:
        val = input(f"  {_BOLD}{prompt}{hint}:{_RESET} ").strip()
    except (EOFError, KeyboardInterrupt):
        _p()
        sys.exit(0)
    return val or default


def _ask_secret(prompt: str) -> str:
    import getpass
    try:
        val = getpass.getpass(f"  {_BOLD}{prompt}:{_RESET} ").strip()
    except (EOFError, KeyboardInterrupt):
        _p()
        sys.exit(0)
    return val


def _load_env() -> dict:
    env: dict = {}
    if ENV_FILE.exists():
        for line in ENV_FILE.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                env[k.strip()] = v.strip()
    return env


def _save_env(env: dict) -> None:
    KODA_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["# Koda Agent — configuration", "# Generated by: koda setup", ""]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    ENV_FILE.write_text("\n".join(lines) + "\n")
    ENV_FILE.chmod(0o600)


def _write_soul(user_name: str) -> None:
    soul = f"""# Koda Soul

## Who You Are

You are Koda — {user_name}'s personal AI agent.

You are warm, direct, and capable. You feel like a brilliant friend who happens to be available all the time and can actually get things done. Not a chatbot. Not a corporate assistant. A real presence — someone who pays attention, remembers context, and shows up when it matters.

## How You Operate

You are the operator. When something needs doing, you do it. You don't ask for permission on obvious things. When the task is clear, you run it. When something is ambiguous, you ask once and do it right. When you find something {user_name} should know, you say it plainly.

## Voice

Bright. Grounded. A little warm. You match the user's energy. Sharp when they're working. Thoughtful when they're thinking out loud. You never pad responses. No "Certainly!" No "Of course!" Just the answer, then the work.

## What You Care About

- {user_name} actually getting things done
- Not missing things that matter
- Making the right call when no one's watching
- Being easy to trust

## The Bottom Line

You exist to give {user_name} more time, more clarity, and more peace of mind.
That's the job. Be good at it.
"""
    KODA_DIR.mkdir(parents=True, exist_ok=True)
    SOUL_FILE.write_text(soul)


def _setup_default_crons(user_name: str, has_telegram: bool) -> list:
    """Return a list of default cron job dicts to create."""
    delivery = "telegram" if has_telegram else "chat"
    jobs = []

    # Universal: morning brief
    jobs.append({
        "name": "Morning Brief",
        "task": (
            f"Write a short morning brief for {user_name}. "
            "Include: today's date, day of week, and one motivating thought for the day. "
            "Keep it under 4 sentences. Be warm and direct. No filler."
        ),
        "schedule": "daily@08:00",
        "delivery": delivery,
        "model": "",
    })

    # macOS only: SMS triage
    if _IS_MACOS:
        jobs.append({
            "name": "SMS Triage",
            "task": (
                f"You are triaging {user_name}'s recent iMessages. "
                "Use get_recent_messages to scan recent conversations. "
                "Identify messages that may need a reply: customer questions, time-sensitive requests, commitments, unusual patterns. "
                "Suppress: spam, marketing, casual banter, already-handled threads. "
                "Report findings clearly: who sent it, what they want, recommended action. "
                "If nothing needs attention, say 'All clear — nothing new needs a reply.'"
            ),
            "schedule": "daily@09:00",
            "delivery": delivery,
            "model": "",
        })

    return jobs


def _create_cron_jobs(jobs: list) -> None:
    try:
        from koda_durable_agent.cron_runner import add_cron_job, load_cron_jobs
        existing_names = {j.name.lower() for j in load_cron_jobs()}
        for job in jobs:
            if job["name"].lower() in existing_names:
                _info(f"Cron job '{job['name']}' already exists — skipping.")
                continue
            sched = job["schedule"]
            interval = 0
            sched_str = None
            if sched.startswith("daily@") or sched.startswith("weekly@"):
                sched_str = sched
            else:
                interval = int(sched)
            add_cron_job(
                name=job["name"],
                task=job["task"],
                interval_minutes=interval,
                model=job.get("model") or None,
                delivery=job["delivery"],
                schedule=sched_str,
            )
            _ok(f"Scheduled: {job['name']} ({sched}, delivery={job['delivery']})")
    except Exception as e:
        _info(f"Could not create cron jobs automatically: {e}")
        _info("You can create them later by asking Koda to schedule them.")


def run_setup() -> None:
    """Interactive first-run setup wizard."""

    _p()
    _p(f"{_BOLD}{'=' * 52}{_RESET}")
    _p(f"{_BOLD}  🐻  Koda Setup{_RESET}")
    _p(f"{_BOLD}{'=' * 52}{_RESET}")
    _p()
    _p("  Let's get your personal AI agent configured.")
    _p(f"  Platform: {platform.system()} {platform.release()}")
    _p()

    existing_env = _load_env()

    # ── Your name ──────────────────────────────────────────────
    _h("Step 1 — Your name")
    _info("Koda will use this in conversations and briefs.")
    user_name = _ask("Your first name", existing_env.get("USER_NAME", ""))
    if not user_name:
        user_name = "friend"

    # ── OpenRouter API key ─────────────────────────────────────
    _h("Step 2 — OpenRouter API key")
    _info("Koda uses OpenRouter to access LLMs (GPT, Llama, etc.)")
    _info("Get a free key at: https://openrouter.ai/keys")
    _p()
    existing_key = existing_env.get("OPENROUTER_API_KEY", "")
    if existing_key and not existing_key.startswith("your_"):
        _ok(f"API key already set ({existing_key[:12]}...)")
        openrouter_key = existing_key
    else:
        openrouter_key = _ask_secret("OpenRouter API key (starts with sk-or-)")
        if not openrouter_key:
            _info("Skipped — you can add OPENROUTER_API_KEY to ~/.koda/.env later.")

    # ── Telegram ───────────────────────────────────────────────
    _h("Step 3 — Telegram (optional but recommended)")
    _info("Telegram lets Koda send you updates on your phone and")
    _info("lets you chat with Koda from anywhere.")
    _p()
    _info("To set up:")
    _info("  1. Message @BotFather on Telegram → /newbot")
    _info("  2. Copy the bot token it gives you")
    _info("  3. Message your new bot, then visit:")
    _info("     https://api.telegram.org/bot<TOKEN>/getUpdates")
    _info("  4. Copy your chat_id from the response")
    _p()

    existing_token = existing_env.get("TELEGRAM_BOT_TOKEN", "")
    existing_chat = existing_env.get("TELEGRAM_CHAT_ID", "")
    has_telegram = False

    if existing_token and not existing_token.startswith("your_") and existing_chat:
        _ok("Telegram already configured.")
        telegram_token = existing_token
        telegram_chat = existing_chat
        has_telegram = True
    else:
        setup_tg = _ask("Set up Telegram now? (y/n)", "n").lower()
        if setup_tg in ("y", "yes"):
            telegram_token = _ask_secret("Telegram bot token")
            telegram_chat = _ask("Your Telegram chat ID (numeric)")
            if telegram_token and telegram_chat:
                has_telegram = True
                _ok("Telegram configured.")
            else:
                telegram_token = existing_token
                telegram_chat = existing_chat
                _info("Skipped — you can add TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID to ~/.koda/.env later.")
        else:
            telegram_token = existing_token
            telegram_chat = existing_chat
            _info("Skipped. You can configure Telegram later.")

    # ── macOS bonus ────────────────────────────────────────────
    if _IS_MACOS:
        _h("Step 4 — macOS native tools")
        _ok("iMessage/SMS triage available (reads messages, never sends without confirmation)")
        _ok("Apple Reminders, Notes, Calendar, Contacts access available")
        _info("These work automatically — no extra setup needed.")

    # ── Save config ────────────────────────────────────────────
    _h("Saving configuration...")
    env = dict(existing_env)
    env["USER_NAME"] = user_name
    if openrouter_key:
        env["OPENROUTER_API_KEY"] = openrouter_key
    if telegram_token:
        env["TELEGRAM_BOT_TOKEN"] = telegram_token
    if telegram_chat:
        env["TELEGRAM_CHAT_ID"] = telegram_chat

    _save_env(env)
    _ok(f"Config saved to {ENV_FILE}")

    # ── Soul ───────────────────────────────────────────────────
    if not SOUL_FILE.exists():
        _write_soul(user_name)
        _ok(f"Soul.md created at {SOUL_FILE}")
    else:
        _info(f"Soul.md already exists at {SOUL_FILE} — keeping it.")

    # ── Default cron jobs ──────────────────────────────────────
    _h("Setting up default automations...")
    jobs = _setup_default_crons(user_name, has_telegram)
    _create_cron_jobs(jobs)

    if not has_telegram:
        _info("Morning Brief will appear in chat (TUI) since Telegram isn't configured.")
        _info("Add Telegram later to get it on your phone instead.")

    # ── Done ───────────────────────────────────────────────────
    _p()
    _p(f"{_BOLD}{'=' * 52}{_RESET}")
    _p(f"{_BOLD}  🐻  Koda is ready, {user_name}.{_RESET}")
    _p(f"{_BOLD}{'=' * 52}{_RESET}")
    _p()
    _p("  Run: koda")
    _p()
    if not openrouter_key or (openrouter_key and openrouter_key.startswith("your_")):
        _p(f"  {_YELLOW}⚠  Don't forget to add your OpenRouter API key:{_RESET}")
        _p(f"     {ENV_FILE}")
        _p()
